baseURL : https://fajarr.space/
languageCode : id
title : Fajar A Nugroho

params:
    description: Temukan Tulisan / baca blog dev, kamu juga bisa mendengarkan Podcast
staticDir: static

disqusShortname: fajars-space

tags: []

permalinks:
  blog : /:slug/
  rekomendasi : /:slug/
  
outputs:
    home : ["HTML", "RSS", "JSON"]
